### ISSUE TITLE
Application for adding a new dataset CVQAD

### ISSUE THREAD

**Issue by msm1rnov** [QUALINET/databases#23]
*If you want to add a new database, please edit this template and fill out the following info:*

- `title`: CVQAD (Compressed Video Quality Assessment Dataset)
- `categories`:  `Video`
- `excerpt`: 1,022 compressed videos (including UGC), 32 encoders of 5 compression standards (H.265/HEVC, H.266/VVC, AV1, H.264/AVC, and VP9), 3 target bitrates (1,000 kbps, 2,000 kbps, and 4,000 kbps). 
- `author`: MSU Graphics and Media Lab / A. Antsiferova, S. Lavrushkin, M. Smirnov, A. Gushchin, D. Vatolin, and D. Kulikov
- `partner`: –
- `external_link`: https://videoprocessing.ai/datasets/vqa.html
- `doi`: –
- `access`: Fill out the form on [the CVQAD page](https://videoprocessing.ai/datasets/vqa.html), and the dataset will be sent to you within a few hours.
- `publicly_available`: `true`
- `citation`: If you use this database in your research, we kindly ask that you follow the copyright notice and cite the following paper (you can also find the Bibtex citation template on [the paper page](https://videoprocessing.github.io/vc_dataset_vqm_benchmark))
- `references`: 
    - Anastasia Antsiferova, Sergey Lavrushkin, Maksim Smirnov, Aleksandr Gushchin, Dmitriy Vatolin, and Dmitriy Kulikov, “Video compression dataset and benchmark of learning-based video-quality metrics,” in Thirty-sixth Conference on Neural Informa- tion Processing Systems Datasets and Benchmarks Track, 2022.
- `license`: CCBY
- `contact_name`: Maksim Smirnov
- `contact_email`: vqa@videoprocessing.ai
- `tags`: VQA, IQA, Video quality assessment, Image quality assessment, Compressed quality
- `subjective_scores`: `true`
- `total`: 1,022
- `src`: –
- `hrc`: –
- `ratings`: 320K
- `resolution`: Full HD (1080p )
- `method`: Subjectify.us (Bradley-Terry model)

*If you want, add a longer description of the database here:*

**The CVQA dataset focuses on the compressed video quality assessment problem. It contains 1,022 distorted streams, produced from 36 reference videos, which were originally collected using space-time-complexity clustering from a pool of more that 18,000 videos with the average bitrate of 130 Mbps. Coding artifacts were obtained by compressing videos through several encoders (32 in total) of different compression standards:  H.265/HEVC, H.266/VVC, AV1, H.264/AVC, and VP9. There were two different presets (30 FPS and 1 FPS) and three target bitrates — 1,000 kbps, 2,000 kbps, and 4,000 kbps. More than 320,000 subjective scores were collected through the Subjectify.us crowdsourcing platform, which employs a Bradley-Terry model to transform the results of pairwise voting into a score for each video. Content includes nature, sport, humans close up, gameplays, music videos, water stream or steam, CGI, and user-generated content. Several effects and distortions are also presented: shaking, slow-motion, grain / noisy, too dark / bright regions, macro shooting, captions (text), and extraneous objects.**

*Note: You can use Markdown formatting to highlight text, include external images, create tables, etc. Use the "Preview" function to preview your post.**

**Comment by slhck** [comment]
Thanks for the contribution, the database will be live in a few minutes.

**Comment by slhck** [comment]
https://qualinet.github.io/databases/video/cvqad/
