### ISSUE TITLE
Missing password for the *.zip file

### ISSUE THREAD

**Issue by XiaYi59** [QUALINET/databases#6]
https://qualinet.github.io/databases/video/epfl_polimi_video_quality_assessment_database/

Hello, I downloaded the *.zip file unfortunately, it asks for a password to unzip it. I cannot find it on the webpage since it is indicated: ZIP archive, no password Link: http://vqa.como.polimi.it/QAdatabase/online_DB.zip

Thanks for your help!

**Comment by slhck** [comment]
We are not affiliated with the organization hosting the database. Please contact the institution directly, thanks!

**Comment by slhck** [comment]
On the website it says:

> In order to  obtain the password to download the data please send an email to francesca.desimone@epfl.ch or marco.tagliasacchi@polimi.it

**Comment by XiaYi59** [comment]
Hello, thanks for the update!
