### ISSUE TITLE
Application for adding a new database called RHVD (Real Haze Video Database)

### ISSUE THREAD

**Issue by angelaeaglechu** [QUALINET/databases#9]
*If you want to add a new database, please edit this template and fill out the following info:*

- `title`: Real Haze Video Database
- `categories`: Video
- `excerpt`: A short description (optional)
- `author`: Shenzhen University/Ying Chu, Guoxing Luo, Fan Chen
- `partner`: `true` if you are a QUALINET partner (optional)
- `external_link`: https://drive.google.com/file/d/1zY0LwJ-yNB8u1JTAJU2X7ZkiYXsBX7BF/view?usp=sharing
- `doi`: A Digital Object Identifier (DOI) (optional)
- `access`: The original raw haze videos are downloaded from public websites with free licences. Researcher shall use the Database only for non-commercial research and educational purposes.
- `publicly_available`: true
- `citation`: The database is to be cited in the bibliography as:
Y. Chu, G. Luo, and F. Chen, "A Real Haze Video Database for Haze Level Evaluation," Proc. of the Thirteenth International Conference on Quality of Multimedia Experience, Jun 2021.
- `references`: A list of references (optional), e.g.
    - `[JD20a] John Doe, A sample reference, 2020`
    - `[JD20b] John Doe, Another sample reference, 2020`
- `license`: [RESEARCHER_FULLNAME] (the "Researcher") has requested permission to use the RHVD database (the "Database") at Shenzhen University. In exchange for such permission, Researcher hereby agrees to the following terms and conditions:
The original raw haze videos are downloaded from public websites with free licences. Researcher shall use the Database only for non-commercial research and educational purposes.
Shenzhen University makes no representations or warranties regarding the Database, including but not limited to warranties of non-infringement or fitness for a particular purpose.
Researcher accepts full responsibility for his or her use of the Database and shall defend and indemnify the RHVD team, Shenzhen University, including its employees, trustees, officers and agents, against any and all claims arising from Researcher's use of the Database, including but not limited to Researcher's use of any copies of copyrighted images that he or she may create from the Database.
Researcher may provide research associates and colleagues with access to the Database provided that they first agree to be bound by these terms and conditions.
Shenzhen University reserve the right to terminate Researcher's access to the Database at any time.
If Researcher is employed by a for-profit, commercial entity, Researcher's employer shall also be bound by these terms and conditions, and Researcher hereby represents that he or she is fully authorized to enter into this agreement on behalf of such employer.
- `contact_name`: Ying Chu
- `contact_email`: chuying@szu.edu.cn
- `tags`: Any tags you wish to add (optional)
- `subjective_scores`: true
- `total`: 403
- `src`: The number of SRCs (optional)
- `hrc`: The number of HRCs (optional)
- `ratings`: 40
- `resolution`: 720p, 1080p
- `method`: SS method

Current video quality assessment methods mainly deal with videos with distortions generated in compression or capture process, few researchers focus on perceptual degradation caused by heavy haze in real outdoor scenes. However, assessment of haze level in such application scenario is important. For instance, in the advanced driver assistance system the accurate evaluation of haze level helps to properly release warning signals to drivers, which may avoid latent traffic accidents and save people’s lives. It is necessary to develop studies on haze video quality assessment for real outdoor scenes, and to build benchmark dataset for haze videos. To fill the gap of this benchmark lack, a real haze video database called RHVD was designed and constructed. The dataset contains 403 haze videos captured in real outdoor scenes, which were collected from the Flickr video sharing platform and post-edited in our lab. We conducted subjective quality assessment experiments on the RHVD dataset. Forty non-experts were recruited and asked to rate the haze levels for each of the video in the dataset. The original ratings were screened and normalized to calculate the final subjective scores. The RHVD dataset is free to download from the following website: https://drive.google.com/file/d/1zY0LwJ-yNB8u1JTAJU2X7ZkiYXsBX7BF/view?usp=sharing, or https://pan.baidu.com/s/11p78zwMXmUHMGDj8WDanPA with password RHVD.

**Comment by slhck** [comment]
Published! Thank you for the contribution!
